{pkgs}: {
  deps = [
    pkgs.qhull
    pkgs.gtk3
    pkgs.gobject-introspection
    pkgs.ghostscript
    pkgs.cairo
    pkgs.which
    pkgs.libpng
    pkgs.libjpeg_turbo
    pkgs.ffmpeg-full
    pkgs.pkg-config
    pkgs.playwright-driver
    pkgs.gitFull
    pkgs.zlib
    pkgs.tk
    pkgs.tcl
    pkgs.openjpeg
    pkgs.libxcrypt
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.freetype
    pkgs.geckodriver
    pkgs.bash
    pkgs.glibcLocales
    pkgs.python3
    pkgs.python3Packages.fastapi
    pkgs.python3Packages.uvicorn
    pkgs.nodejs
    pkgs.nodePackages.npm
    pkgs.yarn
    pkgs.expo-cli
  ];
}
